disabled = false
languageCode = "en"
languageName = "English"
weight = 2
title = "lin'blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/logo.png"
secondaryLogo = "img/logo.png"
description = "一个...博客网站"

[params.author]
name = "Jhon Lin"
bio = "lin"
image = "img/head.png"
links = [
    { x-twitter = "https://x.com/yunyouyiyyy" },
    { github = "https://github.com/keloudyunyouyi" },
  ]
